### ISSUE TITLE
Help me - My server close all connections

### ISSUE THREAD

**Issue by pipaun** [uEssentials/uEssentials#161]
I need personal help, my server people can not stay more than 10 minutes playing, all players fall 10 to 10 mintuos. the need to clean the server has a plugin for this? I'm on the verge of closing my server = /

**Comment by Daniil1288** [comment]
this isn't related to uEssentials

**Comment by WGSRangerWolf** [comment]
server specs?




*Have a amazing day,*

*Derrick McLean* (formaly known as waspgod, Rangerwolf)

**Comment by leonardosnt** [comment]
I think that is an unturned/rocket bug, it happen's with me too, when i playing in another servers.

**Comment by pipaun** [comment]
I don't know, i had to reset two times and same error!

**Comment by WGSRangerWolf** [comment]
timeout 1000 in commands.dat?

**Comment by pipaun** [comment]
how can i do it? but the server will closed? how it open again?

**Comment by WGSRangerWolf** [comment]
What timeout does, it set the max ping before kick. It seems if your server cant keep a consistant connection with some people. Setting timeout 1000 in commands.dat
WHat you do is put what i said  in commands.dat and save it then launch the server
I dunno if this works. But there's a bug where /save forces people to leave sometimes. this is due to an unturned bug and nothing related to rocketmod or uessentials.

**Comment by WGSRangerWolf** [comment]
and sometimes there is some commands than can make people leave. When you identify them you make sure those are the less used commands. Unturned always have had this weird bug.

**Comment by pipaun** [comment]
I tried timeout 350, because some players have ping 600, because that player put my server off!
I had read on many websites about that, i think is finally will resolve.

**Comment by Daniil1288** [comment]
Close the issue, then =)
