### ISSUE TITLE
Help to test /pvp

### ISSUE THREAD

**Issue by leonardosnt** [uEssentials/uEssentials#226]
I've added [/pvp](https://github.com/uEssentials/uEssentials/commit/2938158e0caa0524eec9c23acff33201667d35cb), you can disable or enable pvp in server, i've tested and worked, i do getting damage from grenades, traps... but someone can test with guns, because i cant run more than one instance of unturned in my pc.

@WGSRangerWolf 
@Daniil1288

Thanks.

**Comment by Daniil1288** [comment]
@leonardosnt 
Ok I'll try to test that soon, though it's going to be hard because of one strange bug that appeared with the latest update of UNTURNED/ROCKET. 

Players are reporting that they can't join my server sometimes (they have an infinite loading screen and then sometimes they also get kicked to main menu, that doesn't happen every time) and I have a really low player count: 6-16 people? Sometimes 0 (everyone gets kicked but not at the same time).

Same thing happens to me every now and then: infinite loading screen. I found out a way to solve this, but it's temporary: looks like player's data gets corrupted and I have to remove it (console reports that a player is connecting to the server but then instantly gets disconnected). Don't know what's causing this, but the only plugin on my server at the moment is uEssentials, and I don't think that the error is related to the plugin.

Any ideas would be appreciated, though yes, this is not related to the plugin :)

**Comment by leonardosnt** [comment]
@Daniil1288 I think that is corrupted data, nelson said something about that.

**Comment by Daniil1288** [comment]
@leonardosnt yeah... there's no fix? :(

**Comment by Daniil1288** [comment]
@leonardosnt oh btw, where did he say that? I wanna see :D

**Comment by leonardosnt** [comment]
@Daniil1288 I do not remember, i think that was in trello, or reddit.

**Comment by WGSRangerWolf** [comment]
I can test this i guess are u running a server with the pvp?

**Comment by leonardosnt** [comment]
@WGSRangerWolf nop, i don't have a hosting.

**Comment by MortalMonkey** [comment]
If you are still looking for a test server host I am willing to help.  Let me know.
