### ISSUE TITLE
back

### ISSUE THREAD

**Issue by pepixiko** [uEssentials/uEssentials#412]
You can add cooldown to back? when use is instant

**Comment by JustOneMoreBlock** [comment]
Can't this be done using permissions?

**Comment by leonardosnt** [comment]
Delay before death?

**Comment by JustOneMoreBlock** [comment]
When you die and use /back this teleports you instantly.
However, if you die again and use /back again, there is no cooldown.

Probably need a teleport delay and a cooldown delay.

I would rather if the system was changed a bit;

Instead of config options based on time. You can add permission nodes for time.

Example:
```
- uessentials.back.cooldown.30
- uessentials.back.delay.30
- uessentials.tp.cooldown.30
- uessentials.tp.delay.30
```

Basically:
plugin.command.action.time

This will allow for some room for additional perks for like Donations and stuff and reduce the config.json file as you wouldn't need the delays saved.
