### ISSUE TITLE
How do I give /tpa access to my players

### ISSUE THREAD

**Issue by Legend808** [uEssentials/uEssentials#425]
I tried to tp to one of the players on my server by sending /tpa blackleg and when he entered /tpa accept it said he didnt have the permission, whats wrong?
And how do I create a kit

**Comment by leonardosnt** [comment]
essentials.command.tpa
essentials.command.tpa.send
essentials.command.tpa.cancel
essentials.command.tpa.accept
essentials.command.tpa.deny

**Comment by leonardosnt** [comment]
https://github.com/uEssentials/uEssentials/wiki/Command-Reference#tpa

**Comment by Legend808** [comment]
Hey Leaonardo, WHERE EXACTLY DO I ENTER THOSE, IS IT IN UNTURNED CHAT?
sorry caps

**Comment by leonardosnt** [comment]
In Rocket permissions file!?

**Comment by Legend808** [comment]
sorry for the caps above^ was in the middle of something, and doing so will
give all players in my server permission to send tp

**Comment by Legend808** [comment]
​is that right?

On Thu, Sep 1, 2016 at 3:15 PM, Legend DDOL <yourdailydoseoflegend@gmail.com

**Comment by ElMinerTrack** [comment]
Do you have the rocket-tpa plugin or uessentuals? if you have uessentials, i don't know what's wrong but if you have tpa the permission is just tpa.send tpa.accept etc

**Comment by leonardosnt** [comment]
@Legend808 then?...

**Comment by Legend808** [comment]
Well Im using Uessentials, but when someone tries to accept a tp it tells
them something like "you do not have permission to use this command"

**Comment by PoyoPoak** [comment]
Where do I copy and paste those into the permissions XML file? Is there a format I must follow?

**Comment by Johnyknowhow** [comment]
Essential utilizes permissions in order to allow players to run commands. Normally, everyone who joins the server is assigned to permission group "default". Head over to your server folder and find the "Rocket" folder inside. If you installed rocket on your server, you should know where this is. Now open the file "Permissions.config.xml". You should be greeted with something like this:
![permissions](https://cloud.githubusercontent.com/assets/22043505/18299261/2643a6a6-7474-11e6-86f6-362c1fed5a5f.png)
Yours will probably look different than mine as I have already tweaked this permissions file, but it will look similar.

Anyways, you're going to notice that at the top there is a permissions group with the ID "default".
Underneath it, you'll probably see a bunch of other fields, DisplayName (what the player sees if they do /p), Color (The color of their chat), Members (Shows the steam64ID of all the members in the group [unless it's the default group]), and last but definitely not least, a field titled "Permissions".

There should already be a few permissions included in there, but you are probably interested in TPA. If you've installed uEssentials onto your Rocket server, you should just be able to drop this set of permissions next to the permissions already included in default, and you should be good to go:
        <Permission Cooldown="0">essentials.command.tpa</Permission>
        <Permission Cooldown="0">essentials.command.tpa.send</Permission>
        <Permission Cooldown="0">essentials.command.tpa.cancel</Permission>
        <Permission Cooldown="0">essentials.command.tpa.accept</Permission>
        <Permission Cooldown="0">essentials.command.tpa.deny</Permission>

This is pretty much a simple walkthrough on how to give players permissions to use commands.

**Comment by PoyoPoak** [comment]
Very helpful thanks! :D
