### ISSUE TITLE
[Question] How to give items/vehicles to others and possible bug.

### ISSUE THREAD

**Issue by Aceheliflyer** [uEssentials/uEssentials#646]
If I try to give other players items/vehicles it just says `[Alert] Server: You don't have access to this command`.

Here are the permissions granted:
```xml
<Permission Cooldown="0">essentials.command.item</Permission>
<Permission Cooldown="0">essentials.command.vehicle</Permission>
```

I've tried permissions like these but they don't seem to work:
```xml
<Permission Cooldown="0">essentials.command.item.other</Permission>
<Permission Cooldown="0">essentials.command.item.all</Permission>
<Permission Cooldown="0">essentials.command.vehicle.other</Permission>
<Permission Cooldown="0">essentials.command.vehicle.all</Permission>
```

Just one more thing, how can I let staff have access to all warps even if they create a warp?
I have `PerWarpPermission` set to false but doesn't seem to work. I also tried `essentials.warp.all` but that clearly won't work because that's not a set warp.

**Comment by leonardosnt** [comment]
Just saw that I didn't answered you, I'm sorry.

I tested and `/vehicle` and `/items` seems to work fine.

> Just one more thing, how can I let staff have access to all warps even if they create a warp?

I just fixed the PerWarpPermission option. It will be available in the next build here: https://github.com/uEssentials/Builds (if you still need, since it's been a long time since you created this issue)
