### ISSUE TITLE
uEssentials Kits vs Kits

### ISSUE THREAD

**Issue by DarceyCayl** [uEssentials/uEssentials#686]
Hello, I'm working on setting up FeexRanks rewards from Rank Progression.
I currently use kits from uEssentials, but it seems that FeexRanks is based off of the Kits plugin ( https://hub.rocketmod.net/product/kits/ )
I'm wondering if there is a way to use uEssentials kits for the FeexRanks plugin, or if uEssentials would conflict with the Kits plugin if I were to add it to my server.

Any help would be appreciated!

**Comment by persiafighter** [comment]
Hello @DarceyCayl,

FeexRanks would currently have to be modified in order to support uEssentials' kits.

As to your concern if it would conflict, yes. uEssentials loves to override everything, and so it is if you were to add freakynoises' kits plugin, uEssentials would override it so it isn't used. If you were to disable this overriding for the kits plugin, using config.json of uEssentials should do the trick by removing the kits module and disabling the kits command of uEssentials.

Hope this answers your doubts.

**Comment by DarceyCayl** [comment]
Sweet, thanks!

I went ahead and installed the Kits plugin, and created the kits I wanted to use on FeexRanks. The kits from uEssentials do override the Kits plugin, however FeexRanks pulls the kit information from the Kits plugin. So it seems to work out!
