### ISSUE TITLE
Missing text commands

### ISSUE THREAD

**Issue by lvlbgn** [uEssentials/uEssentials#706]
Hello!
I just updated UEssentials to the latest version, generated new files for it, ran my servers, etc, but i couldn't find the textcommands config while i see in config.json that i can enable text command which i just did.

Where is it? How it works with ur new update?
Also can u tell me any details about the latest update?
Also, can you please tell me why rocketmod version isn't contain libraries (newtonsoft) but the release here contains.
Why, which one shall i use then?

**Comment by leonardosnt** [comment]
> I just updated UEssentials to the latest version, generated new files for it, ran my servers, etc, but i couldn't find the textcommands config while i see in config.json that i can enable text command which i just did.

Not sure why this is happening. I'll fix this!

> Also can u tell me any details about the latest update?

For now you can take a look at the commit history here: https://github.com/uEssentials/uEssentials/compare/1.3.4.0...master

> Also, can you please tell me why rocketmod version isn't contain libraries (newtonsoft) but the release here contains.

It's because RocketMod builds uEssentials directly from this repository and does not include any additional file. But you shouldn't need it since Unturned already includes it as a depedency. I have to remember to remove it from the releases from now on.
